# DATA
data_path: data/

# DATASETS
## Kaggle Datasets
lichess_puzzles_dataset_url: https://www.kaggle.com/datasets/lichess/chess-puzzles
lichess_puzzles_dataset_handle: lichess/chess-puzzles
lichess_puzzles_dataset_name: lichess_puzzles

magnus_carlsen_games_dataset_url: https://www.kaggle.com/datasets/dhrubangtalukdar/magnus-carlsen-chess-com-games
magnus_carlsen_games_dataset_handle: dhrubangtalukdar/magnus-carlsen-chess-com-games
magnus_carlsen_games_dataset_name: magnus_carlsen_games

stockfish_position_evaluations_dataset_url: https://www.kaggle.com/datasets/christofferbrandt/stockfish-position-evaluations
stockfish_position_evaluations_dataset_handle: christofferbrandt/stockfish-position-evaluations
stockfish_position_evaluations_dataset_name: stockfish_position_evaluations

# Web Scraping Datasets
lichess_db_eval_dataset_url: https://database.lichess.org/#evals
lichess_db_eval_dataset_download_url: https://database.lichess.org/lichess_db_eval.jsonl.zst
lichess_db_eval_dataset_name: lichess_db_eval

# MODELS
model_path: models/

# CHECKPOINTS
temp_checkpoint_path: temp_checkpoints/

# RESULTS
results_path: results/

# LOGGING
logging_path: logs/
logging_level: debug

# API KEYS
kaggle_username: YOUR KAGGLE USERNAME # Instructions on how to get in "/src/data/download.py".
kaggle_api_key: INSERT API KEY HERE # Instructions on how to get in "/src/data/download.py".
